- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
#####################################
#  --- Dependencies       --------  #
#####################################
- name: Install list of python packages
  apt: 
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - git
    - virtualenvwrapper
    - python-dev
    - python-pip
    - python-setuptools
    - python-numpy
    - python-dev
    - python-pip
    - python-virtualenv
    - python-wheel
    - python-tk
    - python-imaging
    - python3-dev
    - python3-numpy
    - python3-pip
    - python3-setuptools
    - python3-wheel
    - python3-tk
    - python3-imaging
- name: Get updated files from git repository
  become: true
  become_user: "{{ common.user }}"
  git: 
    repo: 'https://github.com/JJorgeDSIC/DRF_Experiments.git'
    dest: "{{ common.project_dir }}/repo"
- name: Install requirements
  become: true
  become_user: "{{ common.user }}"
  pip:
    extra_args: --user
    executable: /usr/bin/pip3 
    requirements: "{{ common.project_dir }}/repo/requirements.txt"
- name: Populating the app
  become: true
  become_user: "{{ common.user }}"
  shell: ./clean.sh
  args:
    chdir: "{{ common.project_dir }}/repo/djangorest/"
- name: Running the app
  become: true
  become_user: "{{ common.user }}"
  shell: nohup python3 manage.py runserver 0.0.0.0:8000 &
  args:
    chdir: "{{ common.project_dir }}/repo/djangorest/"
